USE empicusDB;

DROP TABLE IF EXISTS DATASOURCE_TWEET;
DROP TABLE IF EXISTS DATASOURCE_TYPE;
DROP TABLE IF EXISTS DATASOURCE_CASE;

DROP TABLE IF EXISTS AFTER_EFFECT_OCCURANCE;
DROP TABLE IF EXISTS AFTER_EFFECT;

DROP TABLE IF EXISTS DISEASE_CASE_CONTACT;
DROP TABLE IF EXISTS DISEASE_CASE_CONTACT_TYPE;
DROP TABLE IF EXISTS DISEASE_CASE_DOCUMENT;
DROP TABLE IF EXISTS DISEASE_CASE_STATUS;
DROP TABLE IF EXISTS DISEASE_PHASE;
DROP TABLE IF EXISTS CLINICAL_FEATURE;
DROP TABLE IF EXISTS DISEASE_SYMPTOM;
DROP TABLE IF EXISTS DISEASE_SIGN;
DROP TABLE IF EXISTS DISEASE_CASE;
DROP TABLE IF EXISTS PATHOGEN_STRAIN;
DROP TABLE IF EXISTS DISEASE;
DROP TABLE IF EXISTS DISEASE_TYPE;
DROP TABLE IF EXISTS DISEASE_CATEGORY;

DROP TABLE IF EXISTS TRANSMISSION_MODE;
DROP TABLE IF EXISTS OUTCOME_TYPE;
DROP TABLE IF EXISTS WORK_DOMAIN;

DROP TABLE IF EXISTS PATHOGEN;
DROP TABLE IF EXISTS PATHOGEN_TYPE;
DROP TABLE IF EXISTS PATHOGEN_CATEGORY;

DROP TABLE IF EXISTS MEDICAL_FACILITY;
DROP TABLE IF EXISTS MEDICAL_FACILITY_TYPE;

DROP TABLE IF EXISTS GEO_LOCATION;
DROP TABLE IF EXISTS GEO_ZONE;
DROP TABLE IF EXISTS COUNTRY;

DROP TABLE IF EXISTS DOCUMENT;
DROP TABLE IF EXISTS DOCUMENT_TYPE;
DROP TABLE IF EXISTS DOCUMENT_CATEGORY;

DROP TABLE IF EXISTS BLOCKCHAIN_WALLET_ACCOUNT;
DROP TABLE IF EXISTS BLOCKCHAIN_WALLET_ACCOUNT_TYPE;
DROP TABLE IF EXISTS BLOCKCHAIN_WALLET;
DROP TABLE IF EXISTS BLOCKCHAIN_WALLET_TYPE;

DROP TABLE IF EXISTS USER_ACCOUNT;
DROP TABLE IF EXISTS PARTY_ROLE;
DROP TABLE IF EXISTS PARTY_ROLE_TYPE;
DROP TABLE IF EXISTS PARTY_CLASSIFICATION;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS ORGANIZATION;
DROP TABLE IF EXISTS PARTY;
DROP TABLE IF EXISTS PARTY_TYPE;
DROP TABLE IF EXISTS CLASSIFICATION;
DROP TABLE IF EXISTS CLASSIFICATION_TYPE;
DROP TABLE IF EXISTS ENTITY_STATUS;
DROP TABLE IF EXISTS ENTITY_STATUS_TYPE;

CREATE TABLE ENTITY_STATUS_TYPE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE ENTITY_STATUS ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  TY_ID					INT(11) NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (TY_ID) REFERENCES ENTITY_STATUS_TYPE(ID)
)
ENGINE=InnoDB;

CREATE TABLE CLASSIFICATION_TYPE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE CLASSIFICATION ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  TY_ID				INT(11) NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (TY_ID) REFERENCES CLASSIFICATION_TYPE(ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY_TYPE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  PARENT_TY_ID		INT(11) NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARENT_TY_ID) REFERENCES PARTY_TYPE(ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PARTY_TY_ID	 			INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NOT NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PARTY_U01 (CODE(35)),
	  FOREIGN KEY (PARTY_TY_ID) REFERENCES PARTY_TYPE(ID)
)
ENGINE=InnoDB;

CREATE TABLE ORGANIZATION (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PARTY_ID					INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NOT NULL,
	  BUSINESS_NO				VARCHAR(35) NOT NULL,
	  TAX_ID					VARCHAR(35) NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX ORGANIZATION_U01 (CODE(35)),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY(ID)
)
ENGINE=InnoDB;

CREATE TABLE PERSON (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PARTY_ID					INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  FIRST_NM 					VARCHAR(35) NULL,
	  MIDDLE_NM 				VARCHAR(35) NULL,
	  LAST_NM 					VARCHAR(35) NULL,
	  GENDER					VARCHAR(1) NULL,
	  HEIGHT 					INT(11) NULL,
	  WEIGTH 					INT(11) NULL,
	  TAX_PIN	 				VARCHAR(15) NULL,
	  PASSPORT_NO	 			VARCHAR(15) NULL,
	  PASSPORT_EXP_DT			DATE NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PERSON_U01 (CODE(35)),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY(ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY_CLASSIFICATION ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  PARTY_ID				INT(11) NOT NULL,
	  CLASS_ID				INT(11)	NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  FROM_DT   			DATE NOT NULL,
	  TO_DT   				DATE NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY(ID),
	  FOREIGN KEY (CLASS_ID) REFERENCES CLASSIFICATION_TYPE(ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY_ROLE_TYPE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY_ROLE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  PARTY_ID				INT(11) NOT NULL,
	  PARTY_ROLE_TY_ID		INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  FROM_DT   			DATE NULL,
	  TO_DT   				DATE NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY(ID),
	  FOREIGN KEY (PARTY_ROLE_TY_ID) REFERENCES PARTY_ROLE_TYPE(ID)
)
ENGINE=InnoDB;

CREATE TABLE USER_ACCOUNT (
	ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	PARTY_ID   				INT(11) NOT NULL,
	CODE 					VARCHAR(75) NOT NULL,
	NAME					VARCHAR(75) NOT NULL,
	USER_NM					VARCHAR(75) NOT NULL,
	PASSWORD 				VARCHAR(25) NOT NULL,
	ACCOUNT_EMAIL			VARCHAR(75) NOT NULL,
	SECRET_IV				VARCHAR(75) NOT NULL,
	CIPHER_TEXT				TEXT NOT NULL,
	PASSPHRASE_SALT 		TEXT NOT NULL,
	PASSPHRASE_ITEREATIONS	INT(11) NOT NULL,
	PUBLIC_KEY	        	TEXT NULL,
	LAST_LOGIN_DT        	TIMESTAMP NULL,
	LOCKED_FG 				VARCHAR(1) NOT NULL,
	STATUS         			VARCHAR(1) NOT NULL,
	CREATED_DT        		DATE NOT NULL,
	CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	LAST_MODIFIED_USR       VARCHAR(35) NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (PARTY_ID) REFERENCES PARTY(ID),
	UNIQUE INDEX USER_ACCOUNT_IX1 (USER_NM(75))
)
ENGINE=InnoDB;

CREATE TABLE BLOCKCHAIN_WALLET_TYPE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX BLOCKCHAIN_WALLET_TYPE_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE BLOCKCHAIN_WALLET ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  TY_ID					INT(11) NOT NULL,
	  USER_ID				INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX BLOCKCHAIN_WALLET_U01 (CODE(35)),
	  FOREIGN KEY (TY_ID) REFERENCES BLOCKCHAIN_WALLET_TYPE (ID),
	  FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT (ID)
)
ENGINE=InnoDB;

CREATE TABLE BLOCKCHAIN_WALLET_ACCOUNT_TYPE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX BLOCKCHAIN_WALLET_ACCOUNT_TYPE_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE BLOCKCHAIN_WALLET_ACCOUNT ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  TY_ID					INT(11) NOT NULL,
	  WALLET_ID				INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(255) NOT NULL, 
  	  BALANCE 		        DECIMAL(38,8) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (WALLET_ID) REFERENCES BLOCKCHAIN_WALLET (ID),
	  FOREIGN KEY (TY_ID) REFERENCES BLOCKCHAIN_WALLET_ACCOUNT_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE DOCUMENT_CATEGORY ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX DOCUMENT_CATEGORY_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DOCUMENT_TYPE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CAT_ID				INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX DOCUMENT_TYPE_U01 (CODE(35)),
	  FOREIGN KEY (CAT_ID) REFERENCES DOCUMENT_CATEGORY (ID)
)
ENGINE=InnoDB;

CREATE TABLE DOCUMENT ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  TY_ID					INT(11) NOT NULL,
	  PARTY_ID				INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(255) NOT NULL,
	  DOC_SIZE		      	INT(11) NOT NULL,
	  DOC_TYPE		      	VARCHAR(75) NOT NULL,
	  DOC_CLIENT_PATH		VARCHAR(75) NULL,
	  DOC_SERVER_PATH		VARCHAR(75) NOT NULL, 
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY (ID),
	  FOREIGN KEY (TY_ID) REFERENCES DOCUMENT_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE COUNTRY ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	TEXT NOT NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX COUNTRY_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE GEO_ZONE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  COUNTRY_ID			INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX GEO_ZONE_U01 (CODE(35)),
	  FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID)
)
ENGINE=InnoDB;

CREATE TABLE GEO_LOCATION ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  ZONE_ID				INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL, 
	  LATITUDE		      	VARCHAR(75) NOT NULL, 
	  LONGITUDE		      	VARCHAR(75) NOT NULL,  
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (ZONE_ID) REFERENCES GEO_ZONE (ID)
)
ENGINE=InnoDB;

CREATE TABLE MEDICAL_FACILITY_TYPE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,  
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX MEDICAL_FACILITY_TYPE_U01 (CODE(35))
)
ENGINE=InnoDB; 

CREATE TABLE MEDICAL_FACILITY ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  TY_ID					INT(11) NOT NULL,
	  LOCATION_ID			INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX MEDICAL_FACILITY_U01 (CODE(35)),
	  FOREIGN KEY (TY_ID) REFERENCES MEDICAL_FACILITY_TYPE (ID),
	  FOREIGN KEY (LOCATION_ID) REFERENCES GEO_LOCATION (ID)
)
ENGINE=InnoDB;

CREATE TABLE PATHOGEN_CATEGORY ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PATHOGEN_CATEGORY_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE PATHOGEN_TYPE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CAT_ID				INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PATHOGEN_TYPE_U01 (CODE(35)),
	  FOREIGN KEY (CAT_ID) REFERENCES PATHOGEN_CATEGORY (ID)
)
ENGINE=InnoDB;

CREATE TABLE PATHOGEN ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  TY_ID					INT(11) NOT NULL,
	  STATUS_ID				INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL, 
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (TY_ID) REFERENCES PATHOGEN_TYPE (ID),
	  FOREIGN KEY (STATUS_ID) REFERENCES ENTITY_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE WORK_DOMAIN ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX WORK_DOMAIN_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE OUTCOME_TYPE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX OUTCOME_TYPE_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE TRANSMISSION_MODE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX TRANSMISSION_MODE_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DISEASE_CATEGORY ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX DISEASE_CATEGORY_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DISEASE_TYPE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CAT_ID				INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (CAT_ID) REFERENCES DISEASE_CATEGORY (ID)
)
ENGINE=InnoDB;

CREATE TABLE DISEASE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  TY_ID					INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX DISEASE_U01 (CODE(35)),
	  FOREIGN KEY (TY_ID) REFERENCES DISEASE_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE PATHOGEN_STRAIN ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  DISEASE_ID			INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PATHOGEN_STRAIN_U01 (CODE(35)),
	  FOREIGN KEY (DISEASE_ID) REFERENCES DISEASE (ID)
)
ENGINE=InnoDB;

CREATE TABLE DISEASE_CASE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  STRAIN_ID				INT(11) NOT NULL,
	  LOCATION_ID			INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL, 
	  INFECTED_DT      		DATE NOT NULL,
	  DOB_DT  	    		DATE NOT NULL,
	  HEIGHT		      	DECIMAL(3,2) NOT NULL, 
	  WEIGHT		      	DECIMAL(3,2) NOT NULL, 
	  GENDER		      	VARCHAR(7) NOT NULL, 
	  DESCRIPTION        	VARCHAR(150) NULL,
	  OBSERVATIONS        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (STRAIN_ID) REFERENCES PATHOGEN_STRAIN (ID),
	  FOREIGN KEY (LOCATION_ID) REFERENCES GEO_LOCATION (ID)
)
ENGINE=InnoDB;

CREATE TABLE DISEASE_SIGN (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(75) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE DISEASE_SYMPTOM (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(75) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE CLINICAL_FEATURE ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  SIGN_ID	 			INT(11) NOT NULL,
	  SYMPTON_ID	 		INT(11) NOT NULL,
	  CODE      			VARCHAR(35) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  STATUS         		VARCHAR(1) NOT NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CLINICAL_FEATURE_U01 (CODE(35)),
	  FOREIGN KEY (SIGN_ID) REFERENCES DISEASE_SIGN (ID),
	  FOREIGN KEY (SYMPTON_ID) REFERENCES DISEASE_SYMPTOM (ID)
)
ENGINE=InnoDB;

CREATE TABLE DISEASE_PHASE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(75) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  INSTRUCTIONS				VARCHAR(255) NOT NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE DISEASE_CASE_STATUS (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  FEATURE_ID	 			INT(11) NOT NULL,
	  PHASE_ID	 				INT(11) NULL,
	  STATUS_ID	 				INT(11) NOT NULL,
	  CASE_ID	 				INT(11) NULL,
	  CODE 						VARCHAR(75) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(255) NOT NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  STATUS_DT        			TIMESTAMP NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (CASE_ID) REFERENCES DISEASE_CASE (ID),
	  FOREIGN KEY (PHASE_ID) REFERENCES DISEASE_PHASE (ID),
	  FOREIGN KEY (FEATURE_ID) REFERENCES CLINICAL_FEATURE (ID),
	  FOREIGN KEY (STATUS_ID) REFERENCES ENTITY_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE AFTER_EFFECT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(75) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(255) NOT NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE AFTER_EFFECT_OCCURANCE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  EFFECT_ID	 				INT(11) NOT NULL,
	  CASE_ID	 				INT(11) NULL,
	  CODE 						VARCHAR(75) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  INSTRUCTIONS				VARCHAR(255) NOT NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (EFFECT_ID) REFERENCES AFTER_EFFECT (ID),
	  FOREIGN KEY (CASE_ID) REFERENCES DISEASE_CASE (ID)
)
ENGINE=InnoDB;

CREATE TABLE DISEASE_CASE_CONTACT_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(75) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(255) NOT NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE DISEASE_CASE_CONTACT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CASE_ID	 				INT(11) NOT NULL,
	  LOCATION_ID	 			INT(11) NOT NULL,
	  STATUS_ID	 				INT(11) NOT NULL,
	  CODE 						VARCHAR(75) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  DESCRIPTION				TEXT NOT NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  GENDER		      		VARCHAR(7) NOT NULL, 
	  AGE	 					INT(3) NOT NULL,	
	  CONTACT_DT 				TIMESTAMP NOT NULL,	
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (CASE_ID) REFERENCES DISEASE_CASE (ID),
	  FOREIGN KEY (LOCATION_ID) REFERENCES GEO_LOCATION (ID),
	  FOREIGN KEY (STATUS_ID) REFERENCES ENTITY_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE DISEASE_CASE_DOCUMENT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CASE_ID	 				INT(11) NOT NULL,
	  DOCUMENT_ID	 			INT(11) NULL,
	  STATUS_ID	 				INT(11) NOT NULL,
	  CODE 						VARCHAR(75) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(255) NOT NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (CASE_ID) REFERENCES DISEASE_CASE (ID),
	  FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (ID),
	  FOREIGN KEY (STATUS_ID) REFERENCES ENTITY_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE DATASOURCE_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(75) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(255) NOT NULL,	
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE DATASOURCE_TWEET (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(75) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  TEXT						VARCHAR(255) NOT NULL,	
	  TWEET_DT 					TIMESTAMP NOT NULL,	
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;


CREATE TABLE DATASOURCE_CASE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  TY_ID	 					INT(11) NOT NULL,
	  DATASOURCE_CODE 			VARCHAR(75) NOT NULL,
	  CODE 						VARCHAR(75) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(255) NOT NULL,
	  STATUS         			VARCHAR(1) NOT NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (TY_ID) REFERENCES DATASOURCE_TYPE (ID)
)
ENGINE=InnoDB;